linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    #    - gosec
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - structcheck
    - unconvert
    - varcheck
  enable-all: false
run:
  skip-files:
    - schema.go
    - pulumiManifest.go
  timeout: 10m
